Web Lottery Application/users/views.py
# IMPORTS
from flask import Blueprint, render_template, flash, redirect, url_for
from app import db
from models import User
from users.forms import RegisterForm

# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')


# VIEWS
# view registration
@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # create signup form object
    form = RegisterForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # if this returns a user, then the email already exists in database

        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists')
            return render_template('users/register.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        role='user')

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        # sends user to login page
        return redirect(url_for('users.login'))
    # if request method is GET or form not valid re-render signup page
    return render_template('users/register.html', form=form)


# view user login
@users_blueprint.route('/login')
def login():
    return render_template('users/login.html')


# view user account
@users_blueprint.route('/account')
def account():
    return render_template('users/account.html',
                           acc_no="PLACEHOLDER FOR USER ID",
                           email="PLACEHOLDER FOR USER EMAIL",
                           firstname="PLACEHOLDER FOR USER FIRSTNAME",
                           lastname="PLACEHOLDER FOR USER LASTNAME",
                           phone="PLACEHOLDER FOR USER PHONE")

Web Lottery Application/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CSC2031</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>

    <style>
    .table {
      margin-left: auto;
      margin-right: auto;
    }
    </style>

    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                       <div class="navbar-end">
                            <a href="{{ url_for('index') }}" class="navbar-item">
                               Home
                            </a>
                            <a href="{{ url_for('users.register') }}" class="navbar-item">
                                Register
                            </a>
                            <a href="{{ url_for('users.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('lottery.lottery') }}" class="navbar-item">
                                Lottery
                            </a>
                            <a href="{{ url_for('admin.admin') }}" class="navbar-item">
                                Admin
                            </a>
                            <a href="{{ url_for('users.account') }}" class="navbar-item">
                                Account
                            </a>
                            {#TODO: LOGOUT#}
                            <a href="" class="navbar-item">
                                Logout
                            </a>
                       </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>
</html>